# Generated by Django 2.2.2 on 2019-07-02 07:19

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_auto_20190521_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feature2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feature3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feature4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feature5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price1',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
