# Generated by Django 2.2.2 on 2019-07-02 07:36

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_auto_20190702_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Color',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
