# Generated by Django 2.2.2 on 2019-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price1',
        ),
        migrations.AlterField(
            model_name='product',
            name='Color',
            field=models.TextField(),
        ),
    ]
