# Generated by Django 2.2.2 on 2019-07-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_auto_20190702_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Speciality',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='StandardSize',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='WhatInTheBox',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Max_Price',
            field=models.TextField(blank=True),
        ),
    ]
