# Generated by Django 2.2.2 on 2019-06-27 08:11

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
